### ISSUE TITLE
Bug: Apps context menu disappearing

### ISSUE THREAD

**Issue by lost-in-action** [Erisa/Cliptok#111]
https://github.com/Erisa/Cliptok/blob/664527a0e48e59f75b8b3d0ca3ddf8b704ac307b/Program.cs#L170 could switching to global commands solve the issue?

**Comment by Erisa** [comment]
I doubt it. I've seen the bug happen with bots that have global commands all the same.

**Comment by lost-in-action** [comment]
Does it happens with bots using other libs? I know some bots using discord.js not having this issue after restarting
But whatever, no matter the library, I agree on a Discord bug, it shouldn't do that regardless.

Also, that's only a suggestion and I'm sure you already though of it lol but anyway, may you try to report/ask on Discord Developers / Discord API server about it?

**Comment by dongle-the-gadget** [comment]
I think that this might be due to DSharpPlus behavior of trying to override all commands upon registering.

**Comment by Erisa** [comment]
I was under the impression that was the most reliable way to do things.
If anyone has any suggestions for how I can resolve it in my code then I'm more than happy to give it a try, but if it's a problem with the library or Discord then I'm not going to change anything.

**Comment by Erisa** [comment]
After some extra looking and some observation of the issue happening in servers with far more bots, I have determined it's a problem with the Discord client itself and has nothing to do with the bot restarting or not restarting. Potentially this is caused by client connection problems, and I have found no information to suggest there is anything I can do about it.
