### ISSUE TITLE
Suggestion: replace Dyno's dead chat snippet with an informational warning

### ISSUE THREAD

**Issue by lost-in-action** [Erisa/Cliptok#115]
![image](https://user-images.githubusercontent.com/89212907/143326057-e4891d83-ffcd-4741-9041-226b87952198.png)

Personally, the "dead chat" no one asked for is already annoying, and having the big Dyno message pop up looks even more annoying as it clutters the chat a little bit.

Just my suggestion, is to integrate it to cliptok: so it deletes the "dead chat" message and shows an informational warning! Informational, then auto-warn like mass-emojis. Unless it looks too restrictive for you lol (I can understand)

I believe tracking "ded chat" and "dead chat" should be enough (of course you already have the full list in Dyno).
However I understand the concern if it's harder to implement than mass-emoji detection, like anyone could just say something like "why people say dead chat?": so maybe as a reminder, you could do a full message comparison and add more sentences, or just play on chances of it to happen, by still continuing to check for messages containing those keywords.

**Comment by Erisa** [comment]
This is one that would need further discussion with the mod team, I'll try and remember to relay here if we decide anything.

**Comment by dongle-the-gadget** [comment]
> Just my suggestion, is to integrate it to cliptok: so it deletes the "dead chat" message and shows an informational warning! Informational, then auto-warn like mass-emojis. Unless it looks too restrictive for you lol (I can understand)

I think that we shouldn't just formally warn them for the first time if they don't meet a tier. 
For example if the user isn't Tier 3+ and hasn't said the sentence once, send a message saying that "This might violate rules".
If the user has Tier 3+ or has said "dead chat" once, formally warn them for rule 16.

**Comment by lost-in-action** [comment]
> I think that we shouldn't just formally warn them for the first time if they don't meet a tier.
like mass-emojis as I mentioned

**Comment by Erisa** [comment]
Mass emojis only don't warn if you're a) Tier 0 and b) haven't been pardoned before.
Anything past that one pardon will always warn, though the first infringement will *also* give an information if its the first one (if youre not Tier 0).

**Comment by Erisa** [comment]
After some discussion we don't think there is anything more that can be done here, and generally would not like the idea of warning for "dead chat" messages even after pardon, since it is situational and would require moderator investigation for each case.
Deleting the message is also kind of a pain because not all of the mentions of "dead chat" are the intended recipients of the message.

Closing this in favour of #97 because the conclusion I came to is that we can log these to #investigations to allow moderators to more easily find and deal with these situations, and if it's decided that we want to delete the message too, that will be possible with the system proposed in #97

If you have further commeents, feel free to voice them still
