### ISSUE TITLE
Feature request: Tier 0 Mass Emoji msg delete and notify instead of warn?

### ISSUE THREAD

**Issue by dAKirby309** [Erisa/Cliptok#22]
What if instead of warning a new member (Tier 0) when they post multiple emojis outside of #random-stuff, Cliptok deletes the mass-emoji message and pings the guilty member to say that those belong in #random-stuff, and multiple emojis outside of that channel isn't allowed. A member may not be aware of this, as seems to often be the case. And much of the time, the emoji messages are from people who don't mean to be spammy, but want to test our emojis and things.

And if they do it the second time, is it possible to track that and warn them that time?

**Comment by Erisa** [comment]
Sure, that sounds doable. I'll take a look soon as I can

**Comment by Erisa** [comment]
While creating this I decided to also display the soft warning message for the second offense since it may have been a while and they might need to be reminded again. 

This only shows the first time someone gets a mass emoji warning from the bot since the feature being added. This should help people who aren't tier 0 to 
I had considered adding this to every mass emoji warning message but it would get quite tiring, especially during raids.

Full demo of the feature:

https://user-images.githubusercontent.com/14004943/108404533-e531ea00-7217-11eb-908d-49f33d7b08f3.mp4

**Comment by Erisa** [comment]
edited^

**Comment by Erisa** [comment]
Oops I forgot to tag the issue on the commit.

Fixed with https://github.com/Erisa/Cliptok/commit/84c7a0c995459cdc8091b6f76dc0c31a6e02f59f

**Comment by Erisa** [comment]
added*
