### ISSUE TITLE
Bug: Running auto-warn filters on AutoMod-blocked messages will fail if AutoMod stops a forum channel post from being created

### ISSUE THREAD

**Issue by FloatingMilkshake** [Erisa/Cliptok#224]
An AutoMod block like this:
![image](https://github.com/user-attachments/assets/cb5f1d38-3b76-45f9-962a-f7f8232760ab)
...will lead to a failure to warn with exception `System.ArgumentException: GuildForum channels do not support sending text messages.`

**Comment by Erisa** [comment]
Same as #223, we shouldn't skip sending public messages because they are the fallback mechanism for notifying users of their warning if they have DMs disabled. 

For this one, the two choices are

* Don't run filters on automod flags that are new thread creations.
* Or, put the warning messages in #tech-support.
